# Memory Management in NumPy

the very core of NumPy is the ndarray object.<br>
 We are going to finish ndarray: strides, which will give you memory layout<br>
NumPy arrays can deal not only with numbers but also with various types of data;
 <br>
 we will talk about record arrays and date time arrays.<br>
  Lastly, we will show how to read/write NumPy arrays from/to files.

## Internal memory layout of an ndarray

An instance of class `ndarray` consists of a contiguous one-dimensional segment of computer memory (owned by the array, or by some other object), combined with an indexing scheme that maps `N` integers into the location of an item in the block. The ranges in which the indices can vary is specified by the **shape** of the array. How many bytes each item takes and how the bytes are interpreted is defined by the data-type object associated with the array.

A particularly interesting attribute of the ndarray object is `flags`. Type the following code:

In [ ]:
!pip install numpy

In [3]:
import numpy as np

In [2]:
x = np.array([1, 2, 3])

In [3]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

The `flags` attribute holds information about the memory layout of the array. The `C_CONTIGUOUS` field in the output indicates whether the array was a C-style array. This means that the indexing of this array is done like a C array. This is also called row-major indexing in the case of 2D arrays. This means that, when moving through the array, the row index is incremented first, and then the column index is incremented. In the case of a multidimensional C-style array, the last dimension is incremented first, followed by the last but one, and so on.

Similarly, the `F_CONTIGUOUS` attribute indicates whether the array is a Fortran-style array. Such an array is said to have column-major indexing (R, Julia, and MATLAB use column-major arrays). This means that, when moving through the array, the first index (along the column) is incremented first.

In [4]:
c_array = np.random.rand(10000, 10000) 

In [5]:
f_array = np.asfortranarray(np.random.rand(10000, 10000)) 

In [6]:
def sum_row(x):
    '''
    Given an array `x`, return the sum of its zeroth row.
    '''
    return np.sum(x[0, :])

In [7]:
def sum_col(x):
    '''
    Given an array `x`, return the sum of its zeroth column.
    '''
    return np.sum(x[:, 0])

Now, let's test the performance of the two functions on both the arrays using IPython's %timeit magic function:

In [8]:
%timeit sum_row(c_array) 

7.93 µs ± 345 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
%timeit sum_row(f_array) 

125 µs ± 2.3 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
%timeit sum_col(c_array) 

122 µs ± 1.08 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [11]:
%timeit sum_col(f_array) 

7.57 µs ± 134 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


As we can see, summing up the row of a C array is much faster than summing up its column. This is because, in a C array, elements in a row are laid out in successive memory locations. The opposite is true for a Fortran array, where the elements of a column are laid out in consecutive memory locations.

This is an important distinction and allows you to suitably arrange your data in an array, depending on the kind of algorithm or operation you are performing. Knowing this distinction can help you speed up your code by orders of magnitude.

## Views and Copies

There are primarily two ways of accessing data by slicing and indexing. They are called copies and views: you can either access elements directly from an array, or create a copy of the array that contains only the accessed elements. Since a view is a reference of the original array (in Python, all variables are references), modifying a view modifies the original array too. This is not true for copies.

The `may_share_memory` function in NumPy miscellaneous routines can be used to determine whether two arrays are copies or views of each other. 

Generally, slicing an array creates a view and indexing it creates a copy. Let us study these differences through a few code snippets. First, let's create a random `100x10` array.

In [13]:
x = np.random.rand(100, 10)
x

array([[1.83183442e-01, 5.03727016e-02, 6.91836737e-01, 6.13923627e-01,
        1.65589208e-01, 4.49132210e-01, 2.16924950e-01, 7.74187757e-01,
        4.63904821e-01, 7.74208842e-01],
       [1.31951619e-01, 2.93148677e-01, 6.84048241e-01, 1.83739177e-01,
        7.99416356e-02, 9.19033111e-01, 4.43710461e-01, 4.49154985e-01,
        7.37933924e-01, 6.98654988e-01],
       [4.59235856e-01, 5.04378790e-01, 7.10357961e-01, 1.23245341e-01,
        5.97631128e-01, 7.37284685e-01, 8.75775134e-01, 5.96583366e-01,
        3.42031460e-01, 7.69751267e-01],
       [2.24712354e-01, 4.25445039e-01, 5.69028307e-01, 9.73732544e-02,
        6.75193556e-01, 3.16961238e-01, 1.99143184e-01, 9.27786935e-01,
        4.57317936e-01, 4.46594401e-01],
       [3.77203334e-01, 5.73914536e-01, 6.54710634e-01, 4.33162656e-01,
        6.46938407e-01, 5.82295507e-01, 6.79786881e-02, 1.09091260e-01,
        3.31205620e-01, 7.81785576e-01],
       [9.27846149e-01, 8.22974865e-01, 4.05486924e-01, 8.86290445e-01,
   

Now, let us extract the first five rows of the array and assign them to variable `y`.

In [14]:
y = x[:5, :]
y

array([[0.18318344, 0.0503727 , 0.69183674, 0.61392363, 0.16558921,
        0.44913221, 0.21692495, 0.77418776, 0.46390482, 0.77420884],
       [0.13195162, 0.29314868, 0.68404824, 0.18373918, 0.07994164,
        0.91903311, 0.44371046, 0.44915498, 0.73793392, 0.69865499],
       [0.45923586, 0.50437879, 0.71035796, 0.12324534, 0.59763113,
        0.73728468, 0.87577513, 0.59658337, 0.34203146, 0.76975127],
       [0.22471235, 0.42544504, 0.56902831, 0.09737325, 0.67519356,
        0.31696124, 0.19914318, 0.92778694, 0.45731794, 0.4465944 ],
       [0.37720333, 0.57391454, 0.65471063, 0.43316266, 0.64693841,
        0.58229551, 0.06797869, 0.10909126, 0.33120562, 0.78178558]])

Let us see if `y` is a view of `x`.

In [10]:
np.may_share_memory(x, y)

True

Now let us modify the array `y` and see how it affects `x`. Set all the elements of `y` to zero:

In [52]:
y[:] = 0 

In [53]:
x[:5, :]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

The code snippet prints out five rows of zeros. This is because `y` was just a view, a reference to `x`.

Next, let's create a copy to see the difference. We use the preceding method that uses a random function to create the `x` array, but this time we initialize the `y` array using `numpy.empty` to create an empty array first and then copy the values from `x` to `y`. So, now `y` is not a view/reference of `x` anymore; it's an independent array but has the same values as part of `x`. Let's use the may_share_memory function again to verify that `y` is the copy of `x`:

In [58]:
x = np.random.rand(100, 10)
y = np.empty([5, 10]) 

In [59]:
y[:] = x[:5, :]

In [60]:
np.may_share_memory(x, y)

False

Let's alter the value in `y` and check whether the value of `x` changes as well:

In [61]:
y[:] = 0

In [63]:
x[:5, :]

array([[0.22594285, 0.84943588, 0.63799672, 0.90865088, 0.89087029,
        0.66289172, 0.41134246, 0.46546459, 0.46927432, 0.34504615],
       [0.56702582, 0.04641427, 0.9855564 , 0.40668092, 0.0628503 ,
        0.56129959, 0.35503778, 0.22145278, 0.72152542, 0.70329602],
       [0.26986364, 0.4927989 , 0.4388591 , 0.15837464, 0.65150918,
        0.62545448, 0.47597151, 0.28765198, 0.38625864, 0.56950966],
       [0.08818207, 0.9425105 , 0.59893522, 0.61628436, 0.51038646,
        0.05008038, 0.85750826, 0.55464599, 0.14657257, 0.56587341],
       [0.63737814, 0.30478605, 0.69243957, 0.54875134, 0.55246097,
        0.2616949 , 0.26626916, 0.98765586, 0.80260403, 0.03282723]])

You should see the preceding snippet print out five rows of random numbers as we initialized `x`, so changing `y` to `0` didn't affect `x`.


# How does it use the same memory to change the shape??

## Introducing strides

Strides are the indexing scheme in NumPy arrays, and indicate the number of bytes to jump to find the next element. We all know the performance improvements of NumPy come from a homogeneous multidimensional array object with fixed-size items, the `numpy.ndarray` object. We've talked about the `shape` (dimension) of the `ndarray` object, the data type, and the order (the C-style row-major indexing arrays and the Fortran style column-major arrays.) Now it's time to take a closer look at **strides**.

###  Example

Let's start by creating a NumPy array and changing its shape to see the differences in the strides.

In [11]:
x = np.arange(8, dtype = np.int8)

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int8)

In [13]:
x.strides

(1,)

In [79]:
x.data

A one-dimensional array `x` is created and its data type is NumPy integer 8, which means each element in the array is an 8-bit integer (1 byte each, and a total of 8 bytes). The strides represent the `tuple` of bytes to step in each dimension when traversing an array. In the previous example, it's one dimension, so we obtain the tuple as `(1, )`. Each element is 1 byte apart from its previous element. When we print out `x.data`, we can get the Python buffer object pointing to the start of the data

Change the shape and see the stride change:

In [14]:
x.shape = 2, 4

In [17]:
x.strides

(4, 1)

Now we change the dimensions of `x` to `2x4` and check the strides again. We can see it changes to `(4, 1)`, which means the elements in the first dimension are four bytes apart, and the array need to jump four bytes to find the next row, but the elements in the second dimension are still 1 byte apart, jumping one byte to find the next column. Let's print out `x.data` again, and we can see that the memory layout of the data remains the same, but only the strides change. The same behavior occurs when we change the shape to be three dimensional: `1x4x2` arrays. (What if our arrays are constructed by the Fortran style order? How will the strides change due to changing the shapes? Try to create a column-major array and do the same exercise to check this out.)

In [18]:
x.shape = 1, 4, 2

In [19]:
x.strides

(8, 2, 1)

In [15]:
x.data

In [16]:
my_list = [0,1,2,3,4,5,6,7,8]
my_list[0::2]

[0, 2, 4, 6, 8]

### How can the stride improve our NumPy experience?

So now we know what a stride is, and its relationship to an ndarray object, but how can the stride improve our NumPy experience? Let's do some stride manipulation to get a better sense of this: two arrays are with same content but have different strides:

In [18]:
import numpy as np
x = np.ones((10000, )) 

In [19]:
y = np.ones((1000000, ))[::100]  # 1000000 = 100 * 10000

In [20]:
x.shape, y.shape

((10000,), (10000,))

In [21]:
(x == y).all()

True

We create two NumPy Arrays, `x` and `y`, and do a comparison; we can see that the two arrays are equal. They have the same shape and all the elements are one, but actually the two arrays are different in terms of memory layout. Let's simply use the flags attribute to check the two arrays' memory layout.

In [22]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [23]:
y.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

We can see that the `x` array is continuous in both the C and Fortran order while `y` is not. Let's check the strides for the difference:

In [24]:
x.strides, y.strides

((8,), (800,))

Array `x` is created continuously, so in the same dimension each element is eight bytes apart (the default `dtype` of `numpy.ones` is a 64-bit float); however, `y` is created from a subset of 10000 * 100 for every 100 elements, so the index schema in the memory layout is not continuous.

Even though `x` and `y` have the same shape, each element in `y` is 800 bytes apart from each other. When you use NumPy arrays `x` and `y`, you might not notice the difference in indexing, but the memory layout does affect the performance. Let's use the `%timeit` to check this out:

In [25]:
%timeit x.sum()

4.57 µs ± 66.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [26]:
%timeit y.sum()

22.5 µs ± 701 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Typically with a fixed cache size, when the stride size gets larger, the hit rate (the fraction of memory accessed that finds data in the cache) will be lower, comparatively, while the miss rate (the fraction of memory accessed that has to go to the memory) will be higher. The cache hit time and miss time compose the average data access time. Let's try to look at our example again from the cache perspective. Array `x` with smaller strides is faster than the larger strides of `y`. The reason for the difference in performance is that the CPU is pulling data from the main memory to its cache in blocks, and the smaller stride means fewer transfers are needed. See the following graph for details, where the red line represents the size of the CPU cache, and blue boxes represent the memory layout containing the data.

It's obvious that if `x` and `y` are both required, 100 blue boxes of data, the required cache time for `x` will be less.

<img src="../images/cpu-cache.jpg" alt="cpu-cache" width=500 align="left" />

### Stride in N-dimensional `ndarray`

A segment of memory is inherently 1-dimensional, and there are many different schemes for arranging the items of an N-dimensional array in a 1-dimensional block. NumPy is flexible, and ndarray objects can accommodate any strided indexing scheme. In a strided scheme, the N-dimensional index (`n_0, n_1, ..., n_{N-1}`) corresponds to the offset (in bytes):

$n_{\text{offset}} = \sum_{k=0}^{N-1} s_k n_k$

from the beginning of the memory block associated with the array. Here, $s_k$ are integers which specify the strides of the array.

In [123]:
import numpy as np

In [124]:
x = np.random.rand(3, 4)

In [125]:
x.itemsize, x.nbytes / x.shape[0]

(8, 32.0)

In [126]:
x.strides

(32, 8)

In [127]:
# .flatten() returns numpy array
x.flatten()

array([0.86715172, 0.75103058, 0.59647724, 0.96017377, 0.70260017,
       0.39786388, 0.03984518, 0.12612843, 0.00936317, 0.49894596,
       0.78386359, 0.43940843])

In [128]:
# .flat returns iterator
np.array(x.flat)

array([0.86715172, 0.75103058, 0.59647724, 0.96017377, 0.70260017,
       0.39786388, 0.03984518, 0.12612843, 0.00936317, 0.49894596,
       0.78386359, 0.43940843])

In [129]:
# a stride of 1 is equal to 32 bytes
x[1]

array([0.70260017, 0.39786388, 0.03984518, 0.12612843])

## Conclusion: Why `np.array` not `list`

In [ ]:
x = [1, '2', [1, 2, 3]]
arr = np.array([1, 2, 3])

list: more memory is needed
      homogenous memory in numpy results in more speed  -> different data types
      c_array f_array  ---->  which operations are slow which are fast? which axes?
      default is memory view in numpy -----> no copy
      debug ---> flags, strides, data, (under the hood information)
      
      vectorization --> beutiy, no foor loop, formula == code
      broadcasting --> no broadcasting in python